version: '3'

services:

todoback:
  image: todobackend
  ports: 
    - 3001:3001
todofront:
  image: todofront
  ports: 
    - 3001:3001
  environment:
    REACT_APP_API_HOST=todoback   
  depends_on:
    - todoback
todotests:
  image: todotests
  depends_on:
    - todoback
    - todofront 
  environment:
    FRONT_HOST=todofront
